export default [
  {
    title: 'How It Works',
    cards: [
      {
        text: 'works',
      },
    ],
  },
  {
    title: 'Requested',
    cards: [
      { text: 'Requested item 1' },
      { text: 'Requested item 2' },
      { text: 'Requested item 3' },
      { text: 'Requested item 4' },
      { text: 'Requested item 5' },
      { text: 'Requested item 6' },
      { text: 'Requested item 7' },
      { text: 'Requested item 8' },
      { text: 'Requested item 9' },
      { text: 'Requested item 10' },
      { text: 'Requested item 11' },
      { text: 'Requested item 12' },
      { text: 'Requested item 13' },
      { text: 'Requested item 14' },
      { text: 'Requested item 15' },
      { text: 'Requested item 16' },
      { text: 'Requested item 17' },
      { text: 'Requested item 18' },
      { text: 'Requested item 19' },
      { text: 'Requested item 20' },
      { text: 'Requested item 21' },
      { text: 'Requested item 22' },
      { text: 'Requested item 23' },
      { text: 'Requested item 24' },
      { text: 'Requested item 25' },
      { text: 'Requested item 26' },
      { text: 'Requested item 27' },
      { text: 'Requested item 28' },
      { text: 'Requested item 29' },
      { text: 'Requested item 30' },
      { text: 'Requested item 31' },
      { text: 'Requested item 32' },
      { text: 'Requested item 33' },
      { text: 'Requested item 34' },
      { text: 'Requested item 35' },
      { text: 'Requested item 36' },
      { text: 'Requested item 37' },
      { text: 'Requested item 38' },
      { text: 'Requested item 39' },
      { text: 'Requested item 40' },
      { text: 'Requested item 41' },
      { text: 'Requested item 42' },
      { text: 'Requested item 43' },
      { text: 'Requested item 44' },
      { text: 'Requested item 45' },
      { text: 'Requested item 46' },
      { text: 'Requested item 47' },
      { text: 'Requested item 48' },
      { text: 'Requested item 49' },
      { text: 'Requested item 50' },
    ],
  },
  {
    title: 'Packaging',
    cards: [
      {
        text: 'Good',
      },
    ],
  },
  {
    title: 'Delivered',
    cards: [
      {
        text: 'New Delhi',
      },
    ],
  },
];
